common:
  ft_weight: 
  log_path: tensorboard
model:
  name: DQN
  finetune: False
state:
  dim: 4
train:
  optimizer: Adam  #Adam or SGD
  lr: 1.0e-3
  lr_gamma: 0.1 
  lr_momentum: 0.99
  lr_step_size: 1000
  num_epoch: 10000 
  num_decay_epochs: 3500
  initial_epsilon: 1.0
  final_epsilon: 1.0e-3
  batch_size: 512
  gamma: 0.8
  max_penalty: -1
  target_net: True
  target_copy_intarval: 500
  replay_memory_size: 30000
  double_dqn: True
  reward_clipping: True
  prioritized_replay: True 
  multi_step_learning: False
  multi_step_num: 3
  reward_list: #These parameter are not normalized.
    - 0  #survival
    - 100 #0 #1block
    - 300 #2block
    - 700 #3block
    - 1300 #4block
    - -1300 #game over
  reward_weight: #These parameter are used for DQN_v2
    - 0.01 #1 #bampiness 
    - 0.0 #1 #max height
    - 0.01 #1 #hole_num
tetris:
  board_height: 22
  board_width: 10
  score_list:
    - 0
    - 100
    - 300
    - 700
    - 1300
    - -1300
  max_tetrominoes: 3000
